---
title: "Reading data from the web "
author: "My An Huynh"
date: "2024-10-10"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

```

Get the pieces I actually need 

```{r}
marj_use_df =
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

Practice 
Title was imported as first row in the data. 
```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
cost_living = read_html(url)

cost_living |> 
  html_table(header = TRUE)
```

## CSS selectors 

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
swm_title_vec = 
  swm_html |> 
    html_elements(".ipc-title-link-wrapper .ipc-title__text") |> 
    html_text()

swm_runtime_vec =
swm_html |> 
  html_elements(".dli-title-metadata-item:nth-child(2)") |> 
  html_text()

swm_score_vec =
swm_html |> 
  html_elements(".ipc-rating-star--rating") |> 
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec,
    runtime = swm_runtime_vec,
    score = swm_score_vec
  )
```

Import some books

```{r}
books_html = read_html("https://books.toscrape.com") 

books_title = 
  books_html |> 
  html_elements("h3") |> 
  html_text()

books_price =
  books_html |> 
  html_elements(".price_color") |> 
  html_text()

books_df = 
  tibble(
    title = books_title,
    price = books_price
  )
```

## Use API

Get water data 
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

Get brfss data 
Use query to specify how many rows you want to import (depending on instructions)
```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content()
```
 
Get pokemon data

```{r}
pokemon_df =
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```

