---
title: "Reading data from the web "
author: "My An Huynh"
date: "2024-10-10"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

```

String matching needs to be the exact match. 
```{r}
string_vec = c("My", "name", "is", "Claudia")

str_detect(string_vec, "a")

str_replace(string_vec, "Claudia", "claudia")

str_replace(string_vec, "e", "E")

```

Use ^ to denote the beginning of the string and $ to denote the end of the string.

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "pumpkin")
str_detect(string_vec,"[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-zA-Z]")
```

## Factors

```{r}
sex_vec = factor(c("male", "male", "female", "female"))
as.numeric(sex_vec)

sex_vec = fct_relevel(sex_vec, "male")
```

